resources:
  - name: demo_Git_Repository
    type: GitRepo
    configuration:
      gitProvider: pipeline_demo_git
      path: yosi-q/jfrog-pipeline-demo-sample
      branches:
        include: master

  - name: demo_mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: satoytestingfree
      buildName: pipeline_demo_build
      buildNumber: 1

pipelines:
  - name: demo_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
    - name: s1_step_build
      type: MvnBuild
      configuration:
        resolverSnapshotRepo: xraysample
        resolverReleaseRepo: xraysample
        deployerSnapshotRepo: xraysample
        deployerReleaseRepo: xraysample
        integrations:
          - name: satoytestingfree
        inputResources:
          - name: demo_Git_Repository     # Trigger execution on code commit
      execution:
        onStart:
          - echo "Preparing for work..."
        onSuccess:
          - echo "Job well done!"
        onFailure:
          - echo "uh oh, something went wrong"
        onComplete:                                  #always
          - echo "Cleaning up some stuff"

    - name: s2_publish_build_info
      type: PublishBuildInfo
      configuration:
        inputSteps: 
          - name: s1_step_build
        outputResources: 
          - name: demo_mvn_build_info

    - name: s3_step_final
      type: Bash
      configuration:
        inputSteps:
          - name: s2_publish_build_info               # Execute this step after the prior step
      execution:
        onExecute:
          - echo "Goodbye World!"